-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 15:06:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mentor` (
  `idMentor` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `posicao_cargo` VARCHAR(100) NOT NULL,
  `localizacao` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `foto` MEDIUMBLOB NULL,
  PRIMARY KEY (`idMentor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `idtags` INT NOT NULL,
  `nome_tag` VARCHAR(45) NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mentor_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mentor_has_tags` (
  `Mentor_idMentor` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`Mentor_idMentor`, `tags_idtags`),
  INDEX `fk_Mentor_has_tags_tags1_idx` (`tags_idtags` ASC) VISIBLE,
  INDEX `fk_Mentor_has_tags_Mentor_idx` (`Mentor_idMentor` ASC) VISIBLE,
  CONSTRAINT `fk_Mentor_has_tags_Mentor`
    FOREIGN KEY (`Mentor_idMentor`)
    REFERENCES `mydb`.`Mentor` (`idMentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mentor_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `mydb`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pacotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacotes` (
  `idPacotes` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `preco` FLOAT NOT NULL,
  `itens_inclusos` VARCHAR(200) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `Mentor_idMentor` INT NOT NULL,
  PRIMARY KEY (`idPacotes`),
  INDEX `fk_Pacotes_Mentor1_idx` (`Mentor_idMentor` ASC) VISIBLE,
  CONSTRAINT `fk_Pacotes_Mentor1`
    FOREIGN KEY (`Mentor_idMentor`)
    REFERENCES `mydb`.`Mentor` (`idMentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendario` (
  `idcalendario` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_horario` DATETIME NOT NULL,
  `descricao` TINYTEXT NULL,
  `Mentor_idMentor` INT NOT NULL,
  PRIMARY KEY (`idcalendario`),
  INDEX `fk_calendario_Mentor1_idx` (`Mentor_idMentor` ASC) VISIBLE,
  CONSTRAINT `fk_calendario_Mentor1`
    FOREIGN KEY (`Mentor_idMentor`)
    REFERENCES `mydb`.`Mentor` (`idMentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificado` (
  `idCertificado` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `documento` MEDIUMBLOB NOT NULL,
  `data_envio` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `Mentor_idMentor` INT NOT NULL,
  PRIMARY KEY (`idCertificado`),
  INDEX `fk_Certificado_Mentor1_idx` (`Mentor_idMentor` ASC) VISIBLE,
  CONSTRAINT `fk_Certificado_Mentor1`
    FOREIGN KEY (`Mentor_idMentor`)
    REFERENCES `mydb`.`Mentor` (`idMentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(20) NULL,
  `posicao_cargo` VARCHAR(100) NULL,
  `localizacao` VARCHAR(100) NULL,
  `data_nascimento` DATE NULL,
  `foto` MEDIUMBLOB NULL,
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_tags` (
  `Usuario_idUsuario` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `tags_idtags`),
  INDEX `fk_Usuario_has_tags_tags1_idx` (`tags_idtags` ASC) VISIBLE,
  INDEX `fk_Usuario_has_tags_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_tags_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `mydb`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pacotes_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacotes_has_tags` (
  `Pacotes_idPacotes` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`Pacotes_idPacotes`, `tags_idtags`),
  INDEX `fk_Pacotes_has_tags_tags1_idx` (`tags_idtags` ASC) VISIBLE,
  INDEX `fk_Pacotes_has_tags_Pacotes1_idx` (`Pacotes_idPacotes` ASC) VISIBLE,
  CONSTRAINT `fk_Pacotes_has_tags_Pacotes1`
    FOREIGN KEY (`Pacotes_idPacotes`)
    REFERENCES `mydb`.`Pacotes` (`idPacotes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacotes_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `mydb`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
